#/bin/bash
echo "// File autogenerated, do not modify directly!" > phpstubstr.h
echo "typedef struct { const char * filename; const char * data; } pcbc_stub_data;" >> phpstubstr.h
echo "pcbc_stub_data PCBC_PHP_CODESTR[] = {" >> phpstubstr.h

add_file () {
  echo "{\"[CouchbaseNative]/$1\",\"\\n\" \\" >> phpstubstr.h
  tail -n+2 "stub/$1" | sed 's/\\/\\\\/g' | sed 's/\"/\\\"/g' | sed 's/^\(.*\)$/\"\1\\n\" \\/' >> phpstubstr.h
  echo "\"\"}," >> phpstubstr.h
}

add_file "constants.php"
add_file "connstr.php"
add_file "default_transcoder.php"
add_file "CouchbaseViewQuery.class.php"
add_file "CouchbaseN1qlQuery.class.php"
add_file "CouchbaseCluster.class.php"
add_file "CouchbaseClusterManager.class.php"
add_file "CouchbaseBucket.class.php"
add_file "CouchbaseBucketManager.class.php"
add_file "CouchbaseException.class.php"
add_file "CouchbaseMetaDoc.class.php"

echo "};" >> phpstubstr.h
echo "Generated phpstubstr.h"
